### ISSUE TITLE
Not getting refresh token

### ISSUE THREAD

**Issue by sameerkoradiya21** [murraco/spring-boot-jwt#24]
Hi,

I tried to consume refresh api with `http://localhost:8080/users/refresh` with `Bearer > Generated code at the time of login`

**Comment by kudzaitsapo** [comment]
Yeah, same error here ... got a 403

**Comment by murraco** [comment]
@kudzaitsapo You're probably getting a `403` because you have to be authenticated to use the `user/refresh` endpoint.

@sameerkoradiya21 I need more details if you want me to help you, but the following is working for me:

Get the JWT token:

```sh
curl -X POST 'http://localhost:8080/users/signin?username=admin&password=admin'
```
Now replace `TOKEN` with the result you got from the previous request:

```sh
curl -X GET http://localhost:8080/users/refresh -H 'Authorization: Bearer TOKEN'
```

Let me know how it goes.
